### PR TITLE
Add autocomplete values for PLoT-ME

### PR DESCRIPTION
**Pull request by mchlltt**
Rearranged and added values extensively.

### CODE REVIEW

**Comment by jthrilly** [comment]
Awesome work Mich. Have you got the development environment set up such that you can run the grunt tasks, and create main.min.js?

**Comment by mchlltt** [comment]
Hey Josh, I don't, actually -- I've just been modifying things in Sublime Text. I imagine this would be helpful!

**Comment by jthrilly** [comment]
So does that mean that you are manually editing main.min.js in your pull request? If so, let me know and I'll show you how I automatically generate it...!

**Comment by mchlltt** [comment]
That would be lovely!

**Pull request merged**
